version: "3"
services:
 db:
    container_name: db_projeto_xp
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
  
networks:
  default:
    name: projeto_xp_net