version: "3"
services:
 db:
    container_name: db_projeto_xp
    image: mysql:5.7
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'password'

networks:
  default:
    name: xp_net